#!/usr/bin/env python3
"""Compatibility shim -> remd_uniform_chain_2_new (the canonical implementation).

The canonical REMD implementation lives in ``remd_uniform_chain_2_new.py``.
This module re-exports every attribute of the canonical module (public and
underscore-prefixed) so that:

* existing imports ``import remd_uniform_chain_2 as remd`` keep working,
* helpers such as ``remd._apply_rot`` resolve to the same objects,
* CLI execution ``python remd_uniform_chain_2.py ...`` forwards to ``main()``,
* and ``remd_uniform_chain_2.<name> is remd_uniform_chain_2_new.<name>`` holds
  (object identity, not a fragile byte-for-byte file copy).

Do NOT edit this file's logic; edit the canonical module instead.
"""
from __future__ import annotations

import sys as _sys

import remd_uniform_chain_2_new as _canonical

# Mirror the canonical module's namespace into this module by object identity.
_self = _sys.modules[__name__]
for _name in dir(_canonical):
    if _name.startswith("__"):
        continue
    setattr(_self, _name, getattr(_canonical, _name))

# Provenance marker so callers/tests can confirm this is the shim.
CANONICAL_MODULE = _canonical
del _name, _self

main = _canonical.main


if __name__ == "__main__":
    main()
